[build]
  publish = "."
  command = "echo 'Static site'"

[[redirects]]
  from = "/demo/restaurant"
  to = "/templates/restaurant/index.html"
  status = 200

[[redirects]]
  from = "/demo/salon"
  to = "/templates/salon/index.html"
  status = 200

[[redirects]]
  from = "/demo/cafe"
  to = "/templates/cafe/index.html"
  status = 200
